Add flynn upgrade script
Run the flynn upgrade script to reset state database and ensure that
flynn is up to date.

diff --git a/flynn/build-cluster b/flynn/build-cluster
--- a/flynn/build-cluster
+++ b/flynn/build-cluster
@@ -11,6 +11,7 @@ min_hosts=3
 server_type=4gb.ssd
 ssh_verbose=-q
 logon_id="ubuntu"
+flynn_script="https://dl.flynn.io/install-flynn"
 
 usage() {
   echo "Usage: $(basename $0) [-g server group] [-t server_type] [-i cluster_size] [-n cluster_number] [image_id]" >&2
@@ -144,6 +145,28 @@ cluster_domain=$(cluster_domain ${cloudip_id})
 cluster_logon="${logon_id}@${cluster_domain}"
 
 wait_for_ssh "${cluster_logon}" "${ubuntu_boot_complete_file}"
+
+echo "Download latest installation script to each server"
+for ((i=0; i<${#server_list[*]}; i++)); do
+  echo -n "${server_list[i]} "
+  if ! retry 3 ${SSH} "${cluster_logon}" ${SSH} ${server_list[i]} curl -fsSl -o /tmp/install-flynn "${flynn_script}"
+  then
+    echo "\nscript download on ${server_list[i]} failed with error $?" >&2
+    exit 2
+  fi
+done
+echo
+
+echo "Clean and upgrade each server"
+for ((i=0; i<${#server_list[*]}; i++)); do
+  echo -n "${server_list[i]} "
+  if ! retry 3 ${SSH} "${cluster_logon}" ${SSH} ${server_list[i]} sudo bash /tmp/install-flynn --clean --yes
+  then
+    echo "\nclean on ${server_list[i]} failed with error $?" >&2
+    exit 2
+  fi
+done
+echo
 
 echo "Obtaining discovery token for Cluster ${cluster_domain}"
 
diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -176,6 +176,34 @@ wait_for_ssh() {
   clear_keys ${ssh_target} >/dev/null 2>&1
 }
 
+# Retry a command for a number of times or until it succeeds
+function retry()
+{
+        local n=0
+        local try=$1
+        local cmd="${@: 2}"
+	local exit_value=0
+        [[ $# -le 1 ]] && {
+        echo "Usage $0 <retry_number> <Command>"; }
+
+        until [[ $n -ge $try ]]
+        do
+            if $cmd
+	    then
+		exit_value=$?
+		break
+	    else
+		exit_value=$?
+		echo "Command Fail.."
+		((n++))
+		echo "retry $n ::"
+		sleep 1;
+	    fi
+        done
+	return ${exit_value}
+}
+
+
 # Check that the cli exists and is the correct version
 cli_check() {
   local required_version="2.1.2"
